name: agro_lakehouse
version: "1.0.0"
profile: agro_lakehouse

model-paths: ["models"]
snapshot-paths: ["snapshots"]

models:
  agro_lakehouse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +table_type: iceberg
      +s3_data_dir: "s3://agro-lakehouse-gold/"
