"""Profile all downloaded CSV samples and write findings to docs/data_sources.md."""

from __future__ import annotations

import sys
from pathlib import Path
from datetime import datetime

import pandas as pd
from rich.console import Console
from rich.table import Table

SAMPLES_DIR = Path(__file__).resolve().parent.parent / "data" / "samples"
DOCS_FILE = Path(__file__).resolve().parent.parent / "docs" / "data_sources.md"

console = Console()


def profile_csv(path: Path) -> dict:
    """Return a profile dict for a single CSV file."""
    df = pd.read_csv(path, low_memory=False)
    rows, cols = df.shape
    columns = []
    for col in df.columns:
        null_pct = df[col].isna().mean() * 100
        columns.append(
            {
                "name": col,
                "dtype": str(df[col].dtype),
                "null_pct": round(null_pct, 1),
                "sample": str(df[col].dropna().iloc[0])
                if df[col].notna().any()
                else "—",
            }
        )
    return {
        "path": path,
        "rows": rows,
        "cols": cols,
        "columns": columns,
        "head": df.head(3),
    }


def print_profile(profile: dict) -> None:
    source = profile["path"].parent.name
    filename = profile["path"].name
    console.rule(f"[bold cyan]{source} / {filename}[/bold cyan]")
    console.print(
        f"Shape: [bold]{profile['rows']:,} rows × {profile['cols']} columns[/bold]"
    )

    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("Column")
    table.add_column("Dtype")
    table.add_column("Null %", justify="right")
    table.add_column("Sample value")

    for col in profile["columns"]:
        table.add_row(
            col["name"], col["dtype"], f"{col['null_pct']}%", col["sample"][:80]
        )

    console.print(table)
    console.print("\n[dim]First 3 rows:[/dim]")
    console.print(profile["head"].to_string(index=False))
    console.print()


def build_markdown(profiles: list[dict]) -> str:
    lines = [
        "# Data Source Schemas",
        "",
        f"_Generated by `ingestion/explore.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC_",
        "",
        "> Re-run with `uv run ingestion/explore.py` to refresh.",
        "",
    ]
    for p in profiles:
        source = p["path"].parent.name.upper()
        filename = p["path"].name
        lines += [
            f"## {source} — `{filename}`",
            "",
            f"**Shape:** {p['rows']:,} rows × {p['cols']} columns",
            "",
            "| Column | Dtype | Null % | Sample value |",
            "|--------|-------|--------|--------------|",
        ]
        for col in p["columns"]:
            sample = col["sample"].replace("|", "\\|")[:80]
            lines.append(
                f"| `{col['name']}` | {col['dtype']} | {col['null_pct']}% | {sample} |"
            )
        lines += ["", "**First 3 rows:**", "", "```"]
        lines.append(p["head"].to_string(index=False))
        lines += ["```", ""]
    return "\n".join(lines)


def main() -> None:
    csvs = sorted(SAMPLES_DIR.rglob("*.csv"))

    if not csvs:
        console.print(
            "[yellow]No CSV files found under data/samples/. "
            "Run the download scripts first.[/yellow]"
        )
        sys.exit(0)

    console.print(f"Found [bold]{len(csvs)}[/bold] CSV file(s) to profile.\n")

    profiles = []
    for csv_path in csvs:
        try:
            profile = profile_csv(csv_path)
            print_profile(profile)
            profiles.append(profile)
        except Exception as exc:  # noqa: BLE001
            console.print(f"[red]Error profiling {csv_path}: {exc}[/red]")

    DOCS_FILE.parent.mkdir(parents=True, exist_ok=True)
    DOCS_FILE.write_text(build_markdown(profiles), encoding="utf-8")
    console.print(f"[bold green]Schema summary written to:[/bold green] {DOCS_FILE}")


if __name__ == "__main__":
    main()
